language: android

jdk:
 - oraclejdk8

android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-23.0.0
    - android-23
  licenses:
    - '.+'

script:
 - ./gradlew clean assembleDebug testDebugUnitTest --stacktrace

after_success:
 - ./gradlew :example:all-libraries:jacocoTestReport :example:all-libraries:coveralls --stacktrace

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
